version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0 
  snyk: snyk/snyk@1.5.0 #3rd part orb of snyk
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Installing dependencies
          command: npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Running tests
          command: npm run test
  build-and-push:
    executor: docker/docker 
    parameters:
      tag:
        type: string
    steps:
      - setup_remote_docker 
      - checkout
      - docker/check
      - docker/build:
          image: redplatoon/education-space
          tag: << parameters.tag >>
      - docker/push:
          image: redplatoon/education-space
          tag: << parameters.tag >>
  scan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: redplatoon/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
          tag: "latest" # or any other tag you want to use
      - scan:
          requires:
            - build


  # deploy:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - setup_remote_docker
  #     - heroku/install 
  #     - checkout
  #     - run:
  #         name: Heroku Container Push 
  #         command: |
  #           heroku container:login
  #           heroku container:push web -a bingquan-su-devops
  #           heroku container:release web -a bingquan-su-devops


# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build:
#           filters:
#             branches:
#               only:
#                 - main
#       - test:
#           requires:
#             - build
#           filters:
#             branches:
#               only:
#                 - main
#   deploy_workflow:
#     jobs:
#       - build-and-push:
#           requires:
#             - test
#           filters:
#             tags:
#               only: /^v.*/ 
#             branches:
#               ignore: /.*/
#           context: 
#             - DockerHub
#       - deploy:
#           requires:
#             - build-and-push
#           filters:
#             tags:
#               only: /^v.*/
#             branches:
#               ignore: /.*/

